---
- name: 'prometheus | include asserts'
  include_tasks: 'asserts.yml'

- name: 'prometheus | server install'
  include_tasks: 'prometheus.yml'
  when:
    - prometheus_server_enable is defined
    - prometheus_server_enable == "true"

- name: 'prometheus | Node exporter'
  include_tasks: 'node_exporter.yml'
  when:
    - "'node' in prometheus_exporter_packages"

- name: 'prometheus | MongoDB exporter'
  include_tasks: 'mongodb_exporter.yml'
  when:
    - "'mongodb' in prometheus_exporter_packages"

- name: 'prometheus | MySQL exporter'
  include_tasks: 'mysqld_exporter.yml'
  when:
    - "'mysqld' in prometheus_exporter_packages"

- name: 'prometheus | PostgreSQL exporter'
  include_tasks: 'postgresql_exporter.yml'
  when:
    - "'postgresql' in prometheus_exporter_packages"
