---
- name: 'prometheus | server | restart container'
  docker_container:
    name: prometheus
    restart: yes
  tags: ['prometheus']

- name: 'prometheus | node exporter | restart service'
  systemd:
    name: prometheus-node-exporter.service
    state: restarted
    enabled: yes
  tags: ['prometheus']

- name: 'prometheus | mysqld exporter | restart service'
  systemd:
    name: prometheus-mysqld-exporter.service
    state: restarted
    enabled: yes
  tags: ['prometheus']

- name: 'prometheus | mongodb exporter | restart service'
  systemd:
    name: prometheus-mongodb-exporter.service
    state: restarted
    enabled: yes
  tags: ['prometheus']

- name: 'prometheus | postgres exporter | restart service'
  systemd:
    name: prometheus-postgres-exporter.service
    state: restarted
    enabled: yes
  tags: ['prometheus']

- name: 'prometheus | phpfpm exporter | restart service'
  systemd:
    name: prometheus-phpfpm-exporter.service
    state: restarted
    enabled: yes
  tags: ['prometheus']

- name: 'prometheus | apache exporter | restart service'
  systemd:
    name: prometheus-apache-exporter.service
    state: restarted
    enabled: yes
  tags: ['prometheus']
